[package]
name = "figbget"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
eframe = "0.23.0"
egui_extras ={version = "0.23.0", features= ["datepicker"]}
native-tls = "0.2.11"
rust_xlsxwriter = "0.64.1"
scraper = "0.17.1"
ureq = {version = "2.8.0", features = ["native-tls"]}
