[package]
name = "FIGBGET"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
reqwest = {version = "0.11.21", features = ["blocking"]}
rust_xlsxwriter = "0.51.0"
scraper = "0.17.1"
ureq = "2.8.0"
